"""Sentinel MVP: evidence-aware filtering of GUI-agent history."""

from .contracts import (
    Claim,
    EpistemicStatus,
    EvidenceRef,
    GateOperation,
    InitInput,
    OPERATION_TO_VERDICT,
    PromptOperation,
    SentinelOutput,
    StepInput,
    VERDICT_TO_OPERATION,
    Verdict,
    operation_for,
    verdict_for,
)
from .history_filter import (
    ARCHIVE_MARKER,
    CORRECTION_FOOTER,
    CORRECTION_HEADER,
    MASK_MARKER,
    REPLACE_MARKER,
    HistoryFilter,
    filter_history,
    render_correction_block,
)
from .replay import (
    ReplayValidationError,
    load_and_run_replay_bundle,
    run_replay_bundle,
    run_replay_fixture,
)
from .seed_adapter import (
    SeedAdapterOutput,
    SeedHistoryAdapter,
    adapt_seed_history,
    extract_seed_records,
)

__all__ = [
    "ARCHIVE_MARKER",
    "CORRECTION_FOOTER",
    "CORRECTION_HEADER",
    "MASK_MARKER",
    "REPLACE_MARKER",
    "Claim",
    "EpistemicStatus",
    "EvidenceRef",
    "GateOperation",
    "HistoryFilter",
    "InitInput",
    "OPERATION_TO_VERDICT",
    "PromptOperation",
    "ReplayValidationError",
    "SeedAdapterOutput",
    "SeedHistoryAdapter",
    "SentinelOutput",
    "StepInput",
    "VERDICT_TO_OPERATION",
    "Verdict",
    "filter_history",
    "adapt_seed_history",
    "extract_seed_records",
    "load_and_run_replay_bundle",
    "operation_for",
    "render_correction_block",
    "run_replay_bundle",
    "run_replay_fixture",
    "verdict_for",
]
